### ISSUE TITLE
totalLoad call crashing

### ISSUE THREAD

**Issue by driedger** [KyleRoss/windows-cpu#6]
With the latest version, 0.1.3 I an experiencing an exception at line 139. It looks like ocasionally wmic will return
```
"LoadPercentage

"
```
without a value, so the map function fails.

```
C:\node\DataCollector\node_modules\windows-cpu\index.js:139
            var cpus = res.match(/\d+/g).map(function(x) {
                                        ^
TypeError: Cannot read property 'map' of null
    at C:\node\DataCollector\node_modules\windows-cpu\index.js:13
9:41
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

I fixed this for me by changing line 139 to
```
var cpus = (res.match(/\d+/g)) ? res.match(/\d+/g).map(function(x) { 
    return +(x.trim()); 
}) : [null];
```
but I dont know if this is the best way to handle the error. I'll let you look into it further.

**Comment by KyleRoss** [comment]
Fixed in 0.1.4 which is now published to NPM. Thanks for reporting this issue!
